name: Docker build image
on:
  push:
    branches:
      - main

concurrency:
  group: docker-push
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Set lowercase actor
      run: echo "github_actor=${GITHUB_ACTOR,,}" >> $GITHUB_ENV

    - name: Set image name
      run: echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Set short sha tag
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.github_actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        cache-binary: false

    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/${{ env.image_name }}:latest
          ghcr.io/${{ env.image_name }}:${{ env.sha }}
