name: Build and Release PrusaSlicer

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

concurrency:
  group: prusa-slicer
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.latest_tag.outputs.latest_tag }}
      prusa_latest_tag: ${{ steps.prusa_latest_tag.outputs.prusa_latest_tag }}
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Get the latest release tag of this repository
      id: latest_tag
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2> /dev/null || echo "v0.0.0" )
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

    - name: Get the latest release tag of PrusaSlicer
      id: prusa_latest_tag
      run: |
        prusa_latest_tag=$(curl -s https://api.github.com/repos/prusa3d/PrusaSlicer/releases/latest | jq -r .tag_name)
        echo "prusa_latest_tag=$prusa_latest_tag" >> $GITHUB_OUTPUT

  build-deps:
    needs:
    - get-tags
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/devilpepper/prusaslicer
      env:
        prusa_latest_tag: ${{ needs.get-tags.outputs.prusa_latest_tag }}
    if: needs.get-tags.outputs.latest_tag != needs.get-tags.outputs.prusa_latest_tag
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Clone PrusaSlicer at the latest tag
      run: git clone --depth 1 --branch $prusa_latest_tag https://github.com/prusa3d/PrusaSlicer.git

    - name: Create "lockfile"
      run: find PrusaSlicer/deps -type f | sort | xargs sha256sum > deps.lock

    - uses: actions/cache@v4
      id: cache-deps
      with:
        path: PrusaSlicer/deps/build
        key: deps-${{ hashFiles('deps.lock') }}

    - name: Replace GMP url
      run: sed -i 's|https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2|https://github.com/DevilPepper/PrusaSlicer/releases/download/gmp/gmp-6.2.1.tar.bz2|' PrusaSlicer/deps/+GMP/GMP.cmake

    - name: Replace Eigen hash
      run: sed -i 's|e09b89aae054e9778ee3f606192ee76d645eec82c402c01c648b1fe46b6b9857|4815118c085ff1d5a21f62218a3b2ac62555e9b8d7bacd5093892398e7a92c4b|' PrusaSlicer/deps/+Eigen/Eigen.cmake

    - name: Configure dependencies build
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        mkdir -p PrusaSlicer/deps/build
        cd PrusaSlicer/deps/build
        cmake .. -DDEP_WX_GTK3=ON

    - name: CMakeError.log
      if: failure()
      run: cat PrusaSlicer/deps/build/CMakeFiles/CMakeError.log 1>&2

    - name: Upload CMakeError.log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: dependencies-build-errors
        path: PrusaSlicer/deps/build/CMakeFiles/CMakeError.log

    - name: Build dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd PrusaSlicer/deps/build
        make

  build:
    needs:
    - get-tags
    - build-deps
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/devilpepper/prusaslicer
      env:
        prusa_latest_tag: ${{ needs.get-tags.outputs.prusa_latest_tag }}
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Clone PrusaSlicer at the latest tag
      run: git clone --depth 1 --branch $prusa_latest_tag https://github.com/prusa3d/PrusaSlicer.git

    - name: Create "lockfile"
      run: find PrusaSlicer/deps -type f | sort | xargs sha256sum > deps.lock

    - uses: actions/cache/restore@v4
      with:
        path: PrusaSlicer/deps/build
        key: deps-${{ hashFiles('deps.lock') }}
        fail-on-cache-miss: true

    - uses: actions/cache@v4
      id: cache-build
      with:
        path: PrusaSlicer/build
        key: build-${{ needs.get-tags.outputs.prusa_latest_tag }}

    - name: Configure PrusaSlicer build
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        mkdir -p PrusaSlicer/build
        cd PrusaSlicer/build
        cmake .. \
          -DSLIC3R_STATIC=1 \
          -DSLIC3R_DESKTOP_INTEGRATION=0 \
          -DSLIC3R_GTK=3 \
          -DSLIC3R_PCH=OFF \
          -DCMAKE_PREFIX_PATH=$(pwd)/../deps/build/destdir/usr/local

    - name: CMakeError.log
      if: failure()
      run: cat PrusaSlicer/build/CMakeFiles/CMakeError.log 1>&2

    - name: Upload CMakeError.log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-errors
        path: PrusaSlicer/build/CMakeFiles/CMakeError.log

    - name: Build PrusaSlicer
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        cd PrusaSlicer/build
        make -j4

  test:
    needs:
    - get-tags
    - build-deps
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/devilpepper/prusaslicer
      env:
        prusa_latest_tag: ${{ needs.get-tags.outputs.prusa_latest_tag }}
    continue-on-error: true
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Clone PrusaSlicer at the latest tag
      run: git clone --depth 1 --branch $prusa_latest_tag https://github.com/prusa3d/PrusaSlicer.git

    - name: Create "lockfile"
      run: find PrusaSlicer/deps -type f | sort | xargs sha256sum > deps.lock

    - uses: actions/cache/restore@v4
      with:
        path: PrusaSlicer/deps/build
        key: deps-${{ hashFiles('deps.lock') }}
        fail-on-cache-miss: true

    - name: Build PrusaSlicer
      run: |
        mkdir -p PrusaSlicer/build
        cd PrusaSlicer/build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DSLIC3R_STATIC=1 -DSLIC3R_DESKTOP_INTEGRATION=0 -DSLIC3R_GTK=3 -DSLIC3R_PCH=OFF -DCMAKE_PREFIX_PATH=$(pwd)/../deps/build/destdir/usr/local
        make -j4

    - name: Run tests
      run: |
        cd PrusaSlicer/build
        make test

  publish:
    needs:
    - get-tags
    - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Clone PrusaSlicer at the latest tag
      env:
        prusa_latest_tag: ${{ needs.get-tags.outputs.prusa_latest_tag }}
      run: git clone --depth 1 --branch $prusa_latest_tag https://github.com/prusa3d/PrusaSlicer.git

    - uses: actions/cache/restore@v4
      with:
        path: PrusaSlicer/build
        key: build-${{ needs.get-tags.outputs.prusa_latest_tag }}
        fail-on-cache-miss: true

    - name: Zip it
      run: |
        cd PrusaSlicer
        mkdir -p PrusaSlicer/bin
        cp -r src/platform/unix/*.desktop resources PrusaSlicer/
        cp build/src/prusa-slicer PrusaSlicer/bin/
        tar -cavf PrusaSlicer.tar.gz PrusaSlicer/

    - name: Create release with binaries
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_TAG: ${{ needs.get-tags.outputs.prusa_latest_tag }}
      run: |
        gh release create $GIT_TAG \
          --title "PrusaSlicer $GIT_TAG" \
          --notes "Automated build of PrusaSlicer $GIT_TAG" \
          --latest \
          PrusaSlicer/PrusaSlicer.tar.gz
